import Header from "@/app/header"
import "@/globals.css";
import { NextAuthProvider } from "./providers";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="bg-gray-white ">
                <NextAuthProvider>

                    <Header />
                    <main>
                        <div className="px-20 pt-10 ">
                            {children}
                        </div>
                    </main>
                </NextAuthProvider>

            </body>
        </html>
    )
}