import Header from "@/app/(home)/header"
import "@/globals.css";
import { NextAuthProvider } from "@/app/providers";
import Navbar from "@/app/(home)/_navbar";
export const metadata = {
    title: "FreightDiary",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (<>
        <Header />
        <div className="grid gird-cols-2 ">
            <Navbar />
            <main>
                <div className="px-20 pt-10 ">
                    {children}
                </div>
            </main>
        </div>
    </>
    )
}