import Header from "@/app/(home)/header"
import "@/globals.css";
import { NextAuthProvider } from "@/app/providers";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (<>
        <Header />
        <main>
            <div className="px-20 pt-10 ">
                {children}
            </div>
        </main>
    </>
    )
}