import Header from "@/app/(page)/header"
import "@/globals.css";
import { NextAuthProvider } from "@/app/providers";
import Navbar from "@/app/(page)/_navbar";
export const metadata = {
    title: "FreightDiary",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (<>
        <Header />
        <div className="flex">
            <div className="w-header">
                <Navbar />
            </div>
            <main className="">
                <div className="px-6 py-6 ">
                    {children}
                </div>
            </main>
        </div>
    </>
    )
}