import Header from "@/app/(page)/_header"
import "@/globals.css";
import { Suspense } from "react";
import Loading from "@/app/(page)/loading";
export const metadata = {
    title: "FreightDiary",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (<>
        <Header />
        <Suspense fallback={<Loading />}>
            {children}
        </Suspense>
    </>
    )
}