import "@/globals.css";
import Navbar from "@/app/(page)/(tables)/_navbar";
import { Suspense } from "react";
import Loading from "@/app/(page)/loading";
import HaveOrganization from "./HaveOrganization";
export const metadata = {
  title: "FreightDiary",
  description: "Generated by create next app",
};

export default function TablesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <HaveOrganization>
        <div className="flex">
          <div className="w-header">
            <Navbar />
          </div>
          <main className="w-full">
            <div className="p-6 ">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </main>
        </div>
      </HaveOrganization>
    </div>
  );
}
